### ISSUE TITLE
Veristand 2014 ?

### ISSUE THREAD

**Issue by alekus** [NIVeriStandAdd-Ons/FPGA-Custom-Device#1]
Hello, 

Can it be possible to have this costum device for Veristand 2014 ?

thanks

**Comment by tannerblair** [comment]
We don't build versions of our custom devices for anything before 2015, but if you have access to a later version of LabVIEW you should be able to save the source for 2014 and rebuild it.

**Comment by tannerblair** [comment]
Closing this issue as unsupported.

**Comment by alekus** [comment]
i have try to save it in 2014 but for component are protected by a password :(

**Comment by tannerblair** [comment]
Which VIs are password protected?
