### ISSUE TITLE
Missing documentation on which IRQ to fire

### ISSUE THREAD

**Issue by christinesparks** [NIVeriStandAdd-Ons/FPGA-Custom-Device#9]
The readme states "Addon requires an IRQ to fire on the FPGA before it starts." This should include that the interrupt needs to be fired on #30.

**Comment by cdaughters** [comment]
When I didn't have the IRQ set up (just main FPGA code), I got error 56 which is just a general timeout. The examples in the source were helpful to set up the IRQ on 30. Are these stored anywhere on disk when you install the built .nipkg from Releases? 

It looks like v3.0.5 documents the IRQ address.
![image](https://user-images.githubusercontent.com/34285926/60525782-a9e64e80-9cb4-11e9-8d92-e2316a1523fc.png)

**Comment by eatondan** [comment]
It is documented in the main page per Chris's comment.
